config/routes.rb
Rails.application.routes.draw do
  root 'glossaries#index'

  resources :glossaries
  resources :glossaries do
    resources :categories
    resources :words
  end
  resources :glossaries do
    member do
      get :export
    end
  end
  resources :glossaries do
    member do
      get :export_txt
    end
  end
  resources :glossaries do
    member do
      post :import_txt
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :glossary
  has_many :category_words
  has_many :words, through: :category_words
end

app/models/category_word.rb
class CategoryWord < ApplicationRecord
  belongs_to :word
  belongs_to :category
end

app/models/glossary.rb
class Glossary < ApplicationRecord
  has_many :categories
  has_many :words

  def archived?
    archive == true
  end
end

app/models/word.rb
# Модель Word с валидациями, коллбэками и ассоциациями
class Word < ApplicationRecord
  validates :word, presence: true, uniqueness: { scope: :glossary_id }

  before_validation :strip_whitespace

  belongs_to :glossary

  has_many :category_words
  has_many :categories, through: :category_words

  def strip_whitespace
    self.word = word.strip unless word.nil?
    self.definition = definition.strip unless definition.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_glossary
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = @glossary.categories.order(:name)
  end

  def show
  end

  def new
    @category = @glossary.categories.new
  end

  def edit
  end

  def create
    @category = @glossary.categories.new(category_params)

    if @category.save
      redirect_to [@glossary, @category], notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to [@glossary, @category], notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to glossary_categories_url(@glossary), notice: 'Category was successfully destroyed.'
  end

  private

  def set_glossary
    @glossary = Glossary.find(params[:glossary_id])
  end

  def set_category
    @category = @glossary.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/glossaries_controller.rb
class GlossariesController < ApplicationController
  def index
    @glossaries = Glossary.all.order(:name)
  end

  def show
    @glossary = Glossary.find(params[:id])
    @words = @glossary.words.order(:word)
    if params[:letter].present?
      @words = @words.where("word LIKE ?", "#{params[:letter]}%")
    end
  end


  def new
    @glossary = Glossary.new
  end

  def create
    @glossary = Glossary.new(glossary_params)
    if @glossary.save
      redirect_to @glossary, notice: "Glossary was successfully created."
    else
      render :new, alert: "Glossary could not be created."
    end
  end

  def edit
    @glossary = Glossary.find(params[:id])
  end

  def update
    @glossary = Glossary.find(params[:id])
    if @glossary.update(glossary_params)
      redirect_to @glossary, notice: "Glossary was successfully updated."
    else
      render :edit, alert: "Glossary could not be updated."
    end
  end

  def destroy
    @glossary = Glossary.find(params[:id])
    @glossary.destroy
    redirect_to root_path, notice: "Glossary was successfully deleted."
  end

  def export
    @glossary = Glossary.find(params[:id])
    @words = @glossary.words.order(:word)
    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new
        pdf.font_families.update(
          "OpenSans" => {
            normal: Rails.root.join("app/assets/fonts/OpenSans-Regular.ttf"),
            bold: Rails.root.join("app/assets/fonts/OpenSans-Bold.ttf")
          }
        )
        pdf.font "OpenSans"
        pdf.text @glossary.name
        pdf.text @glossary.description
        @words.each do |word|
          pdf.text "<b>#{word.word}</b> - #{word.definition}", inline_format: true
        end
        send_data pdf.render, filename: 'glossary.pdf', type: 'application/pdf'
      end
    end
  end

  def export_txt
    @glossary = Glossary.find(params[:id])
    @words = @glossary.words.order(:word)

    file_content = @words.map { |word| "#{word.word}\t#{word.definition}" }.join("\n")

    send_data file_content, filename: 'glossary.txt', type: 'text/plain'
  end

  def import_txt
    @glossary = Glossary.find(params[:id])

    if params[:file].present?
      file_content = params[:file].read

      file_content.each_line do |line|
        word, definition = line.chomp.split("\t")
        @glossary.words.create(word: word, definition: definition)
      end

      redirect_to @glossary, notice: "Words were successfully imported."
    else
      redirect_to @glossary, alert: "Please select a file to import."
    end
  end


  private
  def glossary_params
    params.require(:glossary).permit(:name, :description, :archive)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @glossary = Glossary.find(params[:glossary_id])
    @words = @glossary.words.order(:word)
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @words = @words.where(categories: { id: @category.id })
    end
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @glossary = Glossary.find(params[:glossary_id])
    @word = @glossary.words.build
    @categories = @glossary.categories.order(:name)
  end

  def create
    @glossary = Glossary.find(params[:glossary_id])
    @word = @glossary.words.build(word_params)
    if @word.save
      redirect_to glossary_path(@word.glossary), notice: "Word was successfully created."
    else
      render :new, alert: "Word could not be created."
    end
  end

  def edit
    @word = Word.find(params[:id])
    @categories = @word.glossary.categories.order(:name)
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to glossary_path(@word.glossary), notice: "Word was successfully updated."
    else
      render :edit, alert: "Word could not be updated."
    end
  end


  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to glossary_words_path(@word.glossary), notice: "Word was successfully deleted."
  end

  private

  def word_params
    params.require(:word).permit(:word, :definition, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: [@glossary, category]) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', [@glossary, @category] %> |
<%= link_to 'Back', glossary_categories_path(@glossary) %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
<!--      <td><%#= link_to 'Show', [@glossary, category] %></td>-->
      <td><%= link_to 'Редагувати', edit_glossary_category_path(@glossary, category) %></td>
      <td><%= link_to 'Видалити', [@glossary, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Створити категорію', new_glossary_category_path(@glossary) %>
<%= link_to "Повернутися", @glossary %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', glossary_categories_path(@glossary) %>

app/views/glossaries/edit.html.erb
<h1>Edit Glossary</h1>

<%= form_with model: @glossary do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :archive %>
    <%= f.check_box :archive %>
  </div>

  <div class="actions">
    <%= f.submit "Зберегти" %>
  </div>
<% end %>

<%= link_to "Скасувати", glossaries_path %>

app/views/glossaries/index.html.erb
<% if params[:archive] == "true" %>
  <h1>Архів глосаріїв</h1>
  <%= link_to "Show Active Glossaries", glossaries_path %>
<% else %>
  <h1>Глосарії</h1>
  <%= link_to "Show Archived Glossaries", glossaries_path(archive: true) %>
<% end %>


<% if @glossaries.empty? %>
  <p>There are no glossaries yet.</p>
<% else %>
  <ul>
    <% @glossaries.each do |glossary| %>
      <% if params[:archive] == "true" && glossary.archive? || params[:archive] != "true" && !glossary.archive? %>
        <li>
          <%= link_to glossary.name, glossary %>
          <%= link_to "Редагувати", edit_glossary_path(glossary) %>
          <%#= link_to "Delete", glossary, method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>
    <% end %>
  </ul>

<% end %>

<%= link_to "Створити глосарій", new_glossary_path %>

app/views/glossaries/new.html.erb
<h1>Новий глосарій</h1>

<%= form_with model: @glossary do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

<!--  <div class="field">-->
    <%#= f.label :archive %>
    <%#= f.check_box :archive %>
<!--  </div>-->

  <div class="actions">
    <%= f.submit "Створити" %>
  </div>
<% end %>

<%= link_to "Скасувати", glossaries_path %>

app/views/glossaries/show.html.erb
<h1><%= @glossary.name %></h1>

<p><%= @glossary.description %></p>
<%= link_to "Редагувати", edit_glossary_path(@glossary) %><br>

<% if @glossary.archived? %>
  <p>(Archived)</p>
<% end %>


<% if @words.empty? %>
  <p><i>У цьому глосарії ще немає слів.</i></p>
<% else %>
  <% available_letters = @glossary.words.pluck(:word).map { |word| word.mb_chars[0].upcase }.uniq %>
  <% available_letters.each do |letter| %>
    <%= link_to letter, glossary_path(@glossary, letter: letter) %>
  <% end %>
  <%= link_to "Show All", glossary_path(@glossary) %>
  <ul>
    <% @words.each do |word| %>
      <li>
        <b><%= word.word %></b> - <%= word.definition %> | <%= link_to "Edit", edit_glossary_word_path(@glossary, word) %><br>
        <% unless word.categories.empty? %>
          <span>(Категорії: <%= word.categories.map(&:name).join(", ") %>)</span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Категорії", glossary_categories_path(@glossary), class: "button" %>
<%= link_to "Додати слово", new_glossary_word_path(@glossary), class: "button" %>

<%#= link_to "Видалити", @glossary, method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Експорт у PDF", export_glossary_path(@glossary, format: :pdf) %>
<%= link_to "Експорт у TXT", export_txt_glossary_path(@glossary) %>
<br>

<%= link_to "Імпорт з TXT", "#", id: "import-txt-button" %>

<div id="import-txt-form" style="display: none;">
  <%= form_with url: import_txt_glossary_path(@glossary), method: :post, local: true, html: { target: "_blank" } do |form| %>
    <%= form.label :file, "Select a file to import:" %>
    <%= form.file_field :file %>
    <%= form.submit "Import" %>
    <%= button_tag "Скасувати", type: "button", id: "cancel-import-button" %>
  <% end %>
</div>

<script>
    document.getElementById("import-txt-button").addEventListener("click", function() {
        document.getElementById("import-txt-form").style.display = "block";
        document.getElementById("import-txt-button").style.display = "none";
    });

    document.getElementById("cancel-import-button").addEventListener("click", function() {
        document.getElementById("import-txt-form").style.display = "none";
        document.getElementById("import-txt-button").style.display = "block";
    });
</script>

<%= link_to "Повернутися", glossaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGlossarium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="/assets/logo.png">
    <link rel="apple-touch-icon" href="/assets/logo.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,700;1,200&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/edit.html.erb
<h1>Edit Word in <%= @word.glossary.name %></h1>

<%= form_with model: [@word.glossary, @word] do |f| %>
  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_area :definition %>
  </div>

  <div class="field">
    <%= f.label :categories %>
    <%= f.collection_check_boxes :category_ids, @categories, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Back", glossary_path(@word.glossary) %>

app/views/words/index.html.erb
<h1>Words in <%= @glossary.name %></h1>

<% if @words.empty? %>
  <p>У цьому глосарії ще немає слів.</p>
<% else %>
  <table>
    <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
      <th>Categories</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.definition %></td>
        <td><%= word.categories.map(&:name).join(", ") %></td>
        <td>
          <%= link_to "Show", [@glossary, word] %>
          <%= link_to "Edit", edit_glossary_word_path(@glossary, word) %>
          <%= link_to "Delete", glossary_word_path(@glossary, word), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "New Word", new_glossary_word_path(@glossary) %>

app/views/words/new.html.erb
<h1>New Word in <%= @glossary.name %></h1>

<%= form_with model: [@glossary, @word] do |f| %>
  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_area :definition %>
  </div>

  <div class="field">
    <%= f.label :categories %>
    <%= f.collection_check_boxes :category_ids, @categories, :id, :name %>
  </div>


  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

<%= link_to "Back", glossary_path(@glossary) %>

app/views/words/show.html.erb
<h1><%= @word.word %></h1>

<p><%= @word.definition %></p>

<% unless @word.categories.empty? %>
  <p>Categories: <%= @word.categories.map(&:name).join(", ") %></p>
<% end %>

<%= link_to "Edit", edit_glossary_word_path(@word.glossary, @word) %>
<%= link_to "Delete", glossary_word_path(@word.glossary, @word), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Back", glossary_words_path(@word.glossary) %>